# Generated by Django 4.2.5 on 2023-09-10 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100, unique=True)),
                ('salary', models.FloatField(default=0)),
                ('percentage', models.FloatField(default=0)),
            ],
        ),
    ]
